[2021-08-22 14:16:58,730] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.notify 2021-08-22T14:16:33.788795+00:00 [queued]>
[2021-08-22 14:16:58,752] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: download_rocket_launches.notify 2021-08-22T14:16:33.788795+00:00 [queued]>
[2021-08-22 14:16:58,752] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 14:16:58,752] {taskinstance.py:1088} INFO - Starting attempt 1 of 1
[2021-08-22 14:16:58,753] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2021-08-22 14:16:59,052] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): notify> on 2021-08-22T14:16:33.788795+00:00
[2021-08-22 14:16:59,057] {standard_task_runner.py:52} INFO - Started process 350 to run task
[2021-08-22 14:16:59,062] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'download_rocket_launches', 'notify', '2021-08-22T14:16:33.788795+00:00', '--job-id', '20', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/1.rocket_launch_data.py', '--cfg-path', '/tmp/tmpp9a34ara', '--error-file', '/tmp/tmpqrvkpvkd']
[2021-08-22 14:16:59,063] {standard_task_runner.py:77} INFO - Job 20: Subtask notify
[2021-08-22 14:16:59,144] {logging_mixin.py:104} INFO - Running <TaskInstance: download_rocket_launches.notify 2021-08-22T14:16:33.788795+00:00 [running]> on host f91ff2939141
[2021-08-22 14:16:59,230] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=download_rocket_launches
AIRFLOW_CTX_TASK_ID=notify
AIRFLOW_CTX_EXECUTION_DATE=2021-08-22T14:16:33.788795+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-08-22T14:16:33.788795+00:00
[2021-08-22 14:16:59,232] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2021-08-22 14:16:59,233] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'echo "There are now ${ls /tmp/images/ | wc -l) images."']
[2021-08-22 14:16:59,244] {subprocess.py:74} INFO - Output:
[2021-08-22 14:16:59,245] {subprocess.py:78} INFO - bash: -c: line 0: unexpected EOF while looking for matching `"'
[2021-08-22 14:16:59,245] {subprocess.py:78} INFO - bash: -c: line 1: syntax error: unexpected end of file
[2021-08-22 14:16:59,247] {subprocess.py:82} INFO - Command exited with return code 1
[2021-08-22 14:16:59,263] {taskinstance.py:1501} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1157, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1331, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1361, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 176, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-08-22 14:16:59,266] {taskinstance.py:1551} INFO - Marking task as FAILED. dag_id=download_rocket_launches, task_id=notify, execution_date=20210822T141633, start_date=20210822T141658, end_date=20210822T141659
[2021-08-22 14:16:59,559] {local_task_job.py:149} INFO - Task exited with return code 1
